hr_path: /home/james/srvc/data/yuv_videos/                          # Change this!
lr_path: /home/james/srvc/data/content_encoded_videos/              # Change this!
original_path: /home/james/srvc/data/original_videos/               # Change this!
save_path: /home/james/srvc/save/                                   # Change this!
log_path: /home/james/srvc/logs/                                    # Change this!
hr_size: 1920,1080
lr_size: 480,270
crf: 10
start_time: 0
end_time: 600
segment_length: 5
segment_skip: 0
F: 32
scale: 4
patch_size: 5,5
crop: True
epoch: 16
batch_size: 8
lr: 0.0001
beta1: 0.9
beta2: 0.999
L1_loss: False
update_frac: 0.01