hr_path: /home/james/srvc/data/yuv_videos/
lr_path: /home/james/srvc/data/content_encoded_videos/
original_path: /home/james/srvc/data/original_videos/
save_path: /home/james/srvc/save/
log_path: /home/james/srvc/logs/
hr_size: 1920,1080
lr_size: 480,270
crf: 10
start_time: 0
end_time: 600
segment_length: 5
segment_skip: 0
F: 32
scale: 4
patch_size: 5,5
crop: True
epoch: 4
batch_size: 1
lr: 0.0001
beta1: 0.9
beta2: 0.999
L1_loss: False
update_frac: 0.01